#!/command/with-contenv sh

set -euo pipefail
export BF_E="${PWD##*/}/$(basename ${0})"


#======================================================================================================================
# Run oCIS with config options.
#======================================================================================================================

bf-echo "Starting oCIS server."
s6-setuidgid ocis ${OCIS_LIB}/server
