#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Initialise oCIS.
#======================================================================================================================

if [ -z `ls ${OCIS_CONFIG}` ] ; then

    bf-echo "Initialising oCIS..."
    s6-setuidgid ocis ocis \
        ocis init \
        --insecure true \
        --config-path /config \
        --admin-password ${OCIS_ADMIN_PASSWORD}
    bf-done

else

    bf-debug "oCIS already initialised."

fi
