#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Initialise oCIS.
#======================================================================================================================

if [ -z `ls ${OCIS_CONFIG}` ] ; then

    bf-echo "Initialising oCIS..."
    s6-setuidgid ocis ${OCIS_LIB}/init
    bf-done

else

    bf-debug "oCIS already initialised."

fi
